name: "Build Redocker Actions Images"

on:
  workflow_run:
    workflows: ["Build Redocker Minimal Images"]
    types:
      - completed

jobs:
  redocker-actions:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        ci:
          - "github"
          - "forgejo"
          - "gitlab"
        version:
          - "4.3"
        type:
          - "minimal"
        target:
          - "linux"
          - "windows"
          - "web"
          #- "android" Nacked in #2 for License Reasons
          #- "macos"   Nacked in #3 for License Reasons
          #- "ios"     Nacked in #3 for License Reasons
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Image
        uses: docker/build-push-action@v6
        with:
          context: "./actions/${{ matrix.type }}/${{ matrix.ci }}"
          push: true
          build-args: |
            REDOT_VERSION=${{ matrix.version }}
            REDOT_TARGET=${{ matrix.target }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            ghcr.io/redot-engine/redocker/actions/${{ matrix.type }}/${{ matrix.ci }}/${{ matrix.target }}-${{ matrix.version }}:latest
            ghcr.io/redot-engine/redocker/actions/${{ matrix.type }}/${{ matrix.ci }}/${{ matrix.target }}-${{ matrix.version }}:${{ github.run_number }}
