name: "Build Redocker Minimal Images"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  redocker:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        version:
          - "4.3"
        type:
          - "minimal"
        target:
          - "linux"
          - "windows"
          - "web"
          #- "android" Nacked in #2 for License Reasons
          #- "macos"   Nacked in #3 for License Reasons
          #- "ios"     Nacked in #3 for License Reasons
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache Redot Binary
        uses: actions/cache@v4
        with:
          path: minimal/redot
          key: redot-${{ matrix.version }}-binary
          restore-keys: |
            redot-${{ matrix.version }}-binary
      - name: Prepare Binary
        run: |
          [ -e minimal/redot ] && exit 0
          file=$(
            curl -s https://api.github.com/repos/Redot-Engine/redot-engine/releases/tags/redot-${{ matrix.version }}-stable \
            | grep "browser_download_url.*Redot_v.*-stable_linux\.x86_64\.zip" \
            | cut -d '"' -f 4 - \
            | head -n 1
          )
          wget $file -O Redot.zip
          unzip Redot.zip
          mv ./Redot_v*-stable_linux.x86_64 minimal/redot
          rm Redot.zip
      - name: Cache Redot Export Templates
        uses: actions/cache@v4
        with:
          path: minimal/templates
          key: redot-${{ matrix.version }}-templates
          restore-keys: |
            redot-${{ matrix.version }}-templates
      - name: Prepare Export Templates
        run: |
          [ -d minimal/templates ] && exit 0
          file=$(
            curl -s https://api.github.com/repos/Redot-Engine/redot-engine/releases/tags/redot-${{ matrix.version }}-stable \
            | grep "browser_download_url.*Redot_v.*-stable_export_templates\.tpz" \
            | cut -d '"' -f 4 - \
            | head -n 1
          )
          wget $file -O Redot.zip
          unzip Redot.zip -d minimal
          rm -f minimal/templates/*debug*
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Image
        uses: docker/build-push-action@v6
        with:
          context: "./minimal"
          push: true
          build-args: |
            REDOT_VERSION=${{ matrix.version }}
            REDOT_TARGET=${{ matrix.target }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            ghcr.io/redot-engine/redocker/${{ matrix.type }}/${{ matrix.target }}-${{ matrix.version }}:latest
            ghcr.io/redot-engine/redocker/${{ matrix.type }}/${{ matrix.target }}-${{ matrix.version }}:${{ github.run_number }}
