name: "Build Redocker Images"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  redocker:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        version:
          - "4.3"
        target:
          - "linux"
          - "windows"
          - "web"
          # Experimental
          - "android"
          - "macos"
          - "ios"
    permissions:
     contents: read
     packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:redocker"
          push: true
          build-args: |
            REDOT_VERSION=${{ matrix.version }}
            REDOT_TARGET=${{ matrix.target }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
          tags: |
            ghcr.io/redot-engine/redocker/${{ matrix.target }}-${{ matrix.version }}:latest
            ghcr.io/redot-engine/redocker/${{ matrix.target }}-${{ matrix.version }}:${{ github.run_number }}
